name: 'Test with phpunit async'
on:
  workflow_call:
    inputs:
      database-name:
        description: 'Database name'
        required: true
        type: string
      with-fixtures-staging:
        description: 'Runs fixtures:staging -f'
        required: false
        type: boolean
        default: false
      php-version:
        description: 'PHP Version'
        required: false
        type: string
        default: '8.2'
      doctrine-connection-name:
        description: 'Doctrine Connection Name'
        required: false
        type: string
        default: 'default'
      parallel-proceses:
        description: 'Amount of parallel processes'
        required: false
        type: number
        default: 5

    secrets:
      aws-role:
        required: true
      packagist-key:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  tests-phpunit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.aws-role }}
        role-duration-seconds: 3600
        role-session-name: CI
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.DIR }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - run: composer config --auth http-basic.repo.packagist.com token ${PACKAGIST_KEY}
      env:
        PACKAGIST_KEY: ${{ secrets.packagist-key }}
    - name: Add AWS credentials to .env.ci
      run: |
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env.ci
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env.ci
        echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> .env.ci
    - name: Set Testing Key permissions
      run: chmod 600 oauth.private.testing.pem
    - name: Download Translations
      run: test -d "translations" && curl "https://assets.moovly.com/i18n/backend/{en,nl,fr,es}.json" -o "translations/messages.#1.json" || true
    - name: Install dependencies
      run: |
        sed -i "s@{%DATABASE_NAME%}@${DATABASE_NAME}@" .env.ci
        mkdir -p var/log
        export $(grep -v '^#' .env.ci | xargs)
        composer install --ignore-platform-reqs
    - name: Setup ci environment
      run: |
        docker compose -f docker-compose-ci.yml build --pull --progress tty
        docker compose -f docker-compose-ci.yml up -d || docker compose -f docker-compose-ci.yml logs
        docker compose -f docker-compose-ci.yml run --rm nginx ./bin/console c:c --no-warmup --env=dev
        ${{ inputs.with-fixtures-staging }} && docker compose -f docker-compose-ci.yml run --rm nginx ./bin/console fixtures:staging -f --env=dev || true
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s
    - name: Run tests
      run: |
        docker compose -f docker-compose-ci.yml run --rm  nginx vendor/bin/paratest -f -p ${{ inputs.parallel-proceses }}
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs
        path: logs
    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose-ci.yml stop
        docker compose -f docker-compose-ci.yml rm -f
